# Site settings
title: My Portfolio
email: austinsimeone94@gmail.com  
description: "Austin Simeone's Portfolio"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/pub/austin-simeone
  - title: github
    url: http://github.com/austinsimeone
  - title: envelope
    url: mailto:austinsimeone94@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: Cityplace West Blvd
  - line: Dallas, TX 75204

# Build settings
markdown: kramdown
permalink: pretty
